server:
  port: 80

cloud:  aws:    credentials:      use-default-aws-credentials-chain: true
    region:      use-default-aws-region-chain: true
    stack:      auto: false

kms:
  keyArn: "arn:aws:kms:${region}:${accountId}:key/mrk-${keyId}"
  
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error