server:
  port: 80

cloud:
  aws:
    credentials:
      access-key: xxx
      secret-key: xxx
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false

kms:
  keyArn: "arn:aws:kms:xxx:xxx:key/mrk-xxx"
  
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error