server:
  port: 80

cloud:  aws:    credentials:      use-default-aws-credentials-chain: true
    region:      use-default-aws-region-chain: true
    stack:      auto: false

kms:
  keyArn: 
    asymmetric: arn:aws:kms:${region}:${accountId}:key/mrk-${asymmetricKeyId}
    symmetric: "arn:aws:kms:${region}:${accountId}:key/mrk-${symmetricKeyId}"
  
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error